# Generated by Django 4.1.4 on 2023-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_paymenttype_feedetails_courseregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='title_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 1'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_1_data',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE 1 DATA'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE '),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_2_data',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE 2 DATA'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 3'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_3_data',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE 3 DATA'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 4'),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_4_data',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE 4 DATA'),
        ),
    ]
