# Generated by Django 4.1.4 on 2023-01-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_courses_title_1_courses_title_1_data_courses_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='complete_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Updated_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.BigIntegerField(default=0)),
                ('image1', models.ImageField(upload_to='updated/courses_images')),
                ('faculty_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_timing', models.TimeField()),
                ('complete_hours', models.DurationField(blank=True, null=True)),
                ('end_timing', models.TimeField()),
                ('duration_days', models.IntegerField()),
                ('Discription1', models.TextField()),
                ('Discription2', models.TextField(blank=True, null=True)),
                ('Discription3', models.TextField(blank=True, null=True)),
                ('CourseFile', models.FileField(upload_to='CourseFile')),
                ('CourseFile2', models.FileField(blank=True, null=True, upload_to='CourseFile')),
                ('is_active', models.BooleanField(default=False)),
                ('title_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 1')),
                ('title_1_data', models.TextField(blank=True, null=True, verbose_name='TITLE 1 DATA')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE ')),
                ('title_2_data', models.TextField(blank=True, null=True, verbose_name='TITLE 2 DATA')),
                ('title_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 3')),
                ('title_3_data', models.TextField(blank=True, null=True, verbose_name='TITLE 3 DATA')),
                ('title_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE 4')),
                ('title_4_data', models.TextField(blank=True, null=True, verbose_name='TITLE 4 DATA')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursescategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
