# Generated by Django 4.1.4 on 2023-01-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_availableupdatedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableUpdatedCourse',
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together=set(),
        ),
    ]
