# Generated by Django 4.1.4 on 2023-01-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_delete_availableupdatedcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updated_courses',
            name='CourseFile',
            field=models.FileField(blank=True, null=True, upload_to='CourseFile'),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='Discription1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.coursescategory'),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='end_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='updated/courses_images'),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updated_courses',
            name='start_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
